### ISSUE TITLE
mac 电脑上运行不起来，你有成功过吗

### ISSUE THREAD

**Issue by zhonglu900505** [dingxinyang/obs-studio-node-demo#2]

**Comment by dingxinyang** [comment]
> “ obs-studio-node”：“ [https://s3-us-west-2.amazonaws.com/obsstudionodes3.streamlabs.com/osn-0.13.26-release-osx.tar.gz”](https://s3-us-west-2.amazonaws.com/obsstudionodes3.streamlabs.com/osn-0.13.26-release-osx.tar.gz%E2%80%9C)，
> “节点窗口-rendering“：” https://slobs-node-window-rendering.s3-us-west-2.amazonaws.com/node-window-rendering-1.0.15-osx.tar.gz “

我朋友的mac电脑运行成功了，你需要引入node-window-rendering依赖，最好使用yarn引入,
你可以在obsRecorder.js中找到这个代码
```
// NWR在mac上通过IOSurface处理显示渲染
if (getOS() === OS.Mac) {
  nwr = require('node-window-rendering');
}
```

**Comment by huang906691** [comment]
一样运行不起来，报以下错误。
$ electron .
App threw an error during load
Error: dlopen(/Users/huangxiaotao/live/obs-studio-node-demo-master/node_modules/obs-studio-node/obs_studio_client.node, 1): no suitable image found.  Did find:
        /Users/huangxiaotao/live/obs-studio-node-demo-master/node_modules/obs-studio-node/obs_studio_client.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
        /Users/huangxiaotao/live/obs-studio-node-demo-master/node_modules/obs-studio-node/obs_studio_client.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/huangxiaotao/live/obs-studio-node-demo-master/node_modules/obs-studio-node/module.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)

另外看说明是使用yarn安装node-window-rendering，然后换遍了几乎所有的源，都提示找不到。

例如： error An unexpected error occurred: "https://registry.npm.taobao.org/node-window-rendering: Not found"

谷歌了半天也没搞定。

**Comment by dingxinyang** [comment]
> 一样运行不起来，报以下错误。
> $ electron .
> App threw an error during load
> Error: dlopen(/Users/huangxiaotao/live/obs-studio-node-demo-master/node_modules/obs-studio-node/obs_studio_client.node, 1): no suitable image found. Did find:
> /Users/huangxiaotao/live/obs-studio-node-demo-master/node_modules/obs-studio-node/obs_studio_client.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
> /Users/huangxiaotao/live/obs-studio-node-demo-master/node_modules/obs-studio-node/obs_studio_client.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
> at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
> at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
> at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
> at Module.load (internal/modules/cjs/loader.js:992:32)
> at Module._load (internal/modules/cjs/loader.js:885:14)
> at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
> at Module.require (internal/modules/cjs/loader.js:1032:19)
> at require (internal/modules/cjs/helpers.js:72:18)
> at Object. (/Users/huangxiaotao/live/obs-studio-node-demo-master/node_modules/obs-studio-node/module.js:3:13)
> at Module._compile (internal/modules/cjs/loader.js:1152:30)
> 
> 另外看说明是使用yarn安装node-window-rendering，然后换遍了几乎所有的源，都提示找不到。
> 
> 例如： error An unexpected error occurred: "https://registry.npm.taobao.org/node-window-rendering: Not found"
> 
> 谷歌了半天也没搞定。

你可以尝试使用 https://slobs-node-window-rendering.s3-us-west-2.amazonaws.com/node-window-rendering-1.0.12-osx.tar.gz 这个地址

**Comment by dingxinyang** [comment]
> 一样运行不起来，报以下错误。
> $ electron .
> App threw an error during load
> Error: dlopen(/Users/huangxiaotao/live/obs-studio-node-demo-master/node_modules/obs-studio-node/obs_studio_client.node, 1): no suitable image found. Did find:
> /Users/huangxiaotao/live/obs-studio-node-demo-master/node_modules/obs-studio-node/obs_studio_client.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
> /Users/huangxiaotao/live/obs-studio-node-demo-master/node_modules/obs-studio-node/obs_studio_client.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
> at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
> at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
> at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
> at Module.load (internal/modules/cjs/loader.js:992:32)
> at Module._load (internal/modules/cjs/loader.js:885:14)
> at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
> at Module.require (internal/modules/cjs/loader.js:1032:19)
> at require (internal/modules/cjs/helpers.js:72:18)
> at Object. (/Users/huangxiaotao/live/obs-studio-node-demo-master/node_modules/obs-studio-node/module.js:3:13)
> at Module._compile (internal/modules/cjs/loader.js:1152:30)
> 
> 另外看说明是使用yarn安装node-window-rendering，然后换遍了几乎所有的源，都提示找不到。
> 
> 例如： error An unexpected error occurred: "https://registry.npm.taobao.org/node-window-rendering: Not found"
> 
> 谷歌了半天也没搞定。

最新的路径可以去[streamlabs-obs](https://github.com/stream-labs/streamlabs-obs/blob/master/package.json)下查找
